#!/usr/bin/env bash
# redirecting to another page
sudo apt-get update
sudo apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.html
sed -i "/listen 80 default_server/ rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/site-available/default
sudo service nginx restart
