#!/usr/bin/env bash
# displays "Holberton School" 8 times, bad luck and good look 1 time
i=0
while [ $i -lt 10 ]
do
    if [ $i -eq 3 ]; then
        echo "bad luck"
    elif [ $i -eq 7 ]; then
        echo "good luck"
    else
        echo "Holberton School"
    fi
    ((i++))
done